version: '3'

services:
  api:
    container_name: 'sally2_api'
    build: ./
    ports:
    - '5002:5002'
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    container_name: 'postgres_db'
    image: postgres:12
    ports:
    - '5432:5432'
    environment:
      POSTGRES_DB: sally2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always


